FizzBuzzDemo/Models/FizzBuzzViewModel.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FizzBuzzDemo.Models
{
    public class FizzBuzzViewModel
    {
        [DisplayName("Please enter a number")]
        [Required(ErrorMessage ="Please enter a number")]
        [Range(1, 1000, ErrorMessage ="Please enter a number between 0 and 1000")]
        public int Number { get; set; }

        public IPagedList<string> FizzBuzzList { get; set; }
    }
}

FizzBuzzDemo/Controllers/FizzBuzzController.cs
using Business.Interfaces;
using FizzBuzzDemo.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FizzBuzzDemo.Controllers
{
    public class FizzBuzzController : Controller
    {
        private readonly IFizzBuzzService fizzBuzzService;

        public FizzBuzzController(IFizzBuzzService fizzBuzzService)
        {
            this.fizzBuzzService = fizzBuzzService;
        }

        // GET: FizzBuzz
        public ActionResult Index()
        {
            return View("Index");
        }

        public ActionResult GetFizzBuzzList(FizzBuzzViewModel model, int? page)
        {
            if (ModelState.IsValid)
            {
                int pageNumber = page != null ? Convert.ToInt32(page) : 1;
                int pageSize = 10;
                var fizzBuzzList = this.fizzBuzzService.GetFizzBuzzList(model.Number);
                if (fizzBuzzList != null)
                {
                    model.FizzBuzzList = fizzBuzzList.ToPagedList(pageNumber, pageSize);
                }
            }

            return View("Index", model);
        }
    }
}

FizzBuzzDemo/Views/FizzBuzz/Index.cshtml
@model FizzBuzzDemo.Models.FizzBuzzViewModel
@using PagedList.Mvc

@{
    ViewBag.Title = "FizzBuzzDemo";
}

<div class="margin-top-25">
    <div class="container">
        @using (Html.BeginForm("GetFizzBuzzList", "FizzBuzz", FormMethod.Get))
        {
        <div class="row">
            <div class="col-md-3">@Html.LabelFor(m => m.Number)</div>
            <div class="col-md-4">
                @Html.TextBoxFor(m => m.Number, new { @class = "form-control" })
                <div class="validation-message">
                    @Html.ValidationMessageFor(m => m.Number)
                </div>
            </div>
        </div>
        <div class="row margin-top-15">
            <div class="col-md-3"></div>
            <div class="col-md-3"><button type="submit" class="btn btn-info">Submit</button></div>
        </div>
        }
    </div>
    <div class="row margin-top-25">
        @Html.Partial("PartialFizzBuzzList")
    </div>
</div>

FizzBuzzDemo/Views/FizzBuzz/PartialFizzBuzzList.cshtml
@model FizzBuzzDemo.Models.FizzBuzzViewModel
@using PagedList.Mvc

@if (Model != null && Model.FizzBuzzList != null && Model.FizzBuzzList.Count > 0)
{
    <table class="table table-borderless">
        <tr>
            <th>Display value</th>
        </tr>
        @foreach (var item in Model.FizzBuzzList)
        {
            <tr>
                @{
                var displayValArray = item.Split(' ');
                <td>
                    @if (displayValArray.Length > 1)
                    {
                        foreach (var val in displayValArray)
                        {
                            <span class="@val">@val</span>
                        }
                    }
                    else
                    {
                        <span class="item">@item</span>
                    }
                </td>
                }
            </tr>
        }
    </table>

    <div class="pagination">
        Page @(Model.FizzBuzzList.PageCount < Model.FizzBuzzList.PageNumber ? 0 : Model.FizzBuzzList.PageNumber) of @Model.FizzBuzzList.PageCount

        @Html.PagedListPager(Model.FizzBuzzList, page => Url.Action("GetFizzBuzzList", new { Number = Model.Number, page }))
    </div>
}

FizzBuzzDemo/Views/Shared/DisplayTemplates/CanonicalHelperModel.cshtml
@model MvcSiteMapProvider.Web.Html.Models.CanonicalHelperModel
@using System.Web.Mvc.Html
@using MvcSiteMapProvider.Web.Html.Models

@if (Model.CurrentNode != null && !string.IsNullOrEmpty(Model.CurrentNode.CanonicalUrl)) {
    <link rel="canonical" href="@Model.CurrentNode.CanonicalUrl" />
}

FizzBuzzDemo/Views/Shared/DisplayTemplates/MenuHelperModel.cshtml
@model MvcSiteMapProvider.Web.Html.Models.MenuHelperModel
@using System.Web.Mvc.Html
@using MvcSiteMapProvider.Web.Html.Models

<ul id="menu">
    @foreach (var node in Model.Nodes) { 
        <li>@Html.DisplayFor(m => node) 
            @if (node.Children.Any()) {
                @Html.DisplayFor(m => node.Children)
            }
        </li>
    }
</ul>

FizzBuzzDemo/Views/Shared/DisplayTemplates/MetaRobotsHelperModel.cshtml
@model MvcSiteMapProvider.Web.Html.Models.MetaRobotsHelperModel
@using System.Web.Mvc.Html
@using MvcSiteMapProvider.Web.Html.Models

@if (Model.CurrentNode != null && !string.IsNullOrEmpty(Model.CurrentNode.MetaRobotsContent)) {
    <meta name="robots" content="@Model.CurrentNode.MetaRobotsContent" />
}

FizzBuzzDemo/Views/Shared/DisplayTemplates/SiteMapHelperModel.cshtml
@model MvcSiteMapProvider.Web.Html.Models.SiteMapHelperModel
@using System.Web.Mvc.Html
@using MvcSiteMapProvider.Web.Html.Models

<ul class="siteMap">
    @foreach (var node in Model.Nodes) { 
        <li>@Html.DisplayFor(m => node) 
            @if (node.Children.Any()) {
                @Html.DisplayFor(m => node.Children)
            }
        </li>
    }
</ul>

FizzBuzzDemo/Views/Shared/DisplayTemplates/SiteMapNodeModel.cshtml
@model MvcSiteMapProvider.Web.Html.Models.SiteMapNodeModel
@using System.Web.Mvc.Html
@using MvcSiteMapProvider.Web.Html.Models

@if (Model.IsCurrentNode && Model.SourceMetadata["HtmlHelper"].ToString() != "MvcSiteMapProvider.Web.Html.MenuHelper")  { 
    <text>@Model.Title</text>
} else if (Model.IsClickable) { 
    if (string.IsNullOrEmpty(Model.Description))
    {
        <a href="@Model.Url">@Model.Title</a>
    }
    else
    {
        <a href="@Model.Url" title="@Model.Description">@Model.Title</a>
    }
} else { 
    <text>@Model.Title</text>
}

FizzBuzzDemo/Views/Shared/DisplayTemplates/SiteMapNodeModelList.cshtml
@model MvcSiteMapProvider.Web.Html.Models.SiteMapNodeModelList
@using System.Web.Mvc.Html
@using MvcSiteMapProvider.Web.Html.Models

<ul>
    @foreach (var node in Model) { 
        <li>@Html.DisplayFor(m => node) 
            @if (node.Children.Any()) {
                @Html.DisplayFor(m => node.Children)
            }
        </li>
    }
</ul>

FizzBuzzDemo/Views/Shared/DisplayTemplates/SiteMapPathHelperModel.cshtml
@model MvcSiteMapProvider.Web.Html.Models.SiteMapPathHelperModel
@using System.Web.Mvc.Html
@using System.Linq
@using MvcSiteMapProvider.Web.Html.Models

@foreach (var node in Model) { 
    @Html.DisplayFor(m => node);
    
    if (node != Model.Last()) {
        <text> &gt; </text>
    }
}

FizzBuzzDemo/Views/Shared/DisplayTemplates/SiteMapTitleHelperModel.cshtml
@model MvcSiteMapProvider.Web.Html.Models.SiteMapTitleHelperModel
@using System.Web.Mvc.Html
@using MvcSiteMapProvider.Web.Html.Models

@if (Model.CurrentNode != null) {@Model.CurrentNode.Title;}

FizzBuzzDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/CustomStyle.css" rel="stylesheet" />
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Fizz Buzz Demo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>